version: '3.4'

services:
    api:
        build:
            context: api
            target: app
        environment:
            APP_DEBUG: 'true'
            APP_ENV: dev
            APP_SECRET:
        volumes:
            - ./api:/app/
            - /app/var
            - /app/vendor
            - public-api:/app/public/
    web:
        build:
            context: web
            target: app
        environment:
            API_URI: http://nginx:8081
            APP_DEBUG: 'true'
            APP_ENV: dev
            APP_SECRET:
        volumes:
            - ./web:/app/
            - /app/var
            - /app/vendor
            - public-web:/app/public/
        depends_on:
          - api
    nginx:
        image: nginx:1.16.0-alpine
        volumes:
            - ./api/.docker/nginx.conf:/etc/nginx/conf.d/api.conf:ro
            - ./web/.docker/nginx.conf:/etc/nginx/conf.d/web.conf:ro
            - public-api:/app/api/:ro
            - public-web:/app/web/:ro
        ports:
            - 8080:8080
            - 8081:8081
        depends_on:
            - api
            - web

volumes:
    public-api:
    public-web:
