csa_guzzle:
    cache:
        adapter: Csa\GuzzleHttp\Middleware\Cache\Adapter\PsrAdapter
    profiler: '%kernel.debug%'
    clients:
        libero_api:
            config:
                base_uri: '%env(API_URI)%'

